import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const products = [{
  name: 'Roll cake',
  photo: 'roll-cake',
},
{
  name: 'Macarrons',
  photo: 'macarrons',
},
{
  name: 'Cookies',
  photo: 'cookies',
}]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/snail.svg" alt="beki bakes" width={100} height={100} />

        <h1 className={styles.title}>
          Beki Bakes
        </h1>

        <div className={styles.grid}>
          {products.map(product => (
            <a
              key={product.name}
              href="https://nextjs.org/docs"
              className={styles.card}
            >
              <Image
                src={`/photos/${product.photo}.jpg`}
                alt={product.name}
                width={100}
                height={100}
              />
              <h2>{product.name}</h2>
            </a>
          ))}
        </div>
      </main>
    </div>
  )
}
