import {
  Card,
  CardActionArea,
  CardContent,
  CardMedia,
  Container,
  Typography,
  Stack,
  Grid,
  Box,
} from '@material-ui/core'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

const products = [{
  name: 'Roll cake',
  photo: 'roll-cake',
  price: 10,
},
{
  name: 'Macarrons',
  photo: 'macarrons',
  price: 10,
},
{
  name: 'Cookies',
  photo: 'cookies',
  price: 10,
},
{
  name: 'Pound cake',
  photo: 'pound-cake',
  price: 10,
}]

export default function Home() {
  return (
    <Container maxWidth="sm">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Stack sx={{ my: 3 }}>
          <Image src="/snail.svg" alt="beki bakes" width={65} height={65} />
          <Typography
            component="h1"
            align="center"
            color="text.secondary"
            sx={{ fontWeight: 'bold', fontSize: 30 }}
          >
            beki
            <Box component="span">
              bakes
            </Box>
          </Typography>
        </Stack>

        <Grid container spacing={2} sx={{ mb: 2 }}>
          {products.map(product => (
            <Grid
              key={product.name}
              item
              xs={12}
              sm={6}
            >
              <Card sx={{ transition: '0.2s', '&:hover': { transform: 'scale(1.03)' } }}>
                <CardActionArea
                  component="a"
                  href={`/photos/${product.photo}.jpg`}
                >
                  <CardMedia
                    component="img"
                    alt={product.name}
                    title={product.name}
                    image={`/photos/${product.photo}.jpg`}
                    height={230}
                  />
                  <CardContent sx={{ py: 1 }}>
                    <Stack direction="row" justifyContent="space-between">
                      <Typography variant="h6">
                        {product.name}
                      </Typography>
                      <Typography variant="h6">
                        €{product.price}
                      </Typography>
                    </Stack>
                  </CardContent>
                </CardActionArea>
              </Card>
            </Grid>
          ))}
        </Grid>
      </main>
    </Container>
  )
}
